aafield/aafield/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aafieldapp.urls')),
    path('accounts/', include('accounts.urls')),
    url(r'^accounts/login/$', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    url(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),
]

urlpatterns= urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

aafield/aafieldapp/urls.py
from accounts.views import user_login
from aafieldapp.views import  park_list, search, home,parkview,propertyview,emppropertyview,empparkview,updatepropertyview,updateparkview,deleteparkview,addpropertyview,deletepropertyview,bookpropertyview,assignmaintenanceview,addmaintenanceview,addchargesview,addmaintchargesview, payment, viewbookings,addComments, updateComments,customerBooking, cancelBooking,finalPayment
from django.urls import path, re_path
from django.conf.urls import url

from . import views
from .import tables

app_name = 'aafieldapp'

urlpatterns = [
   path('',park_list, name='park_list'),
   path('search', search, name='search'),
   path('park/<id>', parkview, name='parkview'),
    path('employeepark/<id>', empparkview, name='employeeparkview'),
    path('property/<id>/<pid>', propertyview, name='propertyview'),
   path('employeeproperty/<id>', emppropertyview, name='emppropertyview'),
    path('updatepark/<id>', updateparkview, name='updatepark'),
    path('addpark', updateparkview, name='addpark'),
    path('deletepark/<id>', deleteparkview, name='deletepark'),
    path('addproperty/<id>', addpropertyview, name='addproperty'),
    path('updateproperty/<id>', updatepropertyview, name='updateproperty'),
    path('deleteproperty/<id>', deletepropertyview, name='deleteproperty'),
    path('login', user_login, name='login'),
    path('book', bookpropertyview, name='bookproperty'),
    path('maintenance', assignmaintenanceview, name='assignmaintenance'),
    path('maintenance/<id>', addmaintenanceview, name='addmaintenance'),
    path('maintenancecost', addchargesview, name='addcharges'),
    path('maintenancecost/<id>', addmaintchargesview, name='addmaintcharges'),
    path('bookings', viewbookings, name='viewbookings'),

 #path('django.views.static',
                            #(r'^media/(?P<path>.*)', 'serve', {'document_root': settings.MEDIA_ROOT}), ),
    re_path(r'^home/$', home, name='home'),
    path('payment', payment, name='payment'),
    path('finalPayment', finalPayment, name='finalPayment'),

 path('addComments/<id>', addComments, name='addComments'),
    path('updateComments', updateComments, name='updateComments'),
    path('customerBooking', customerBooking, name='customerBooking'),
    path('cancelBooking/<id>', cancelBooking, name='cancelBooking'),
]

aafield/aafieldapp/forms.py
from django import forms
from .models import Parks,Park_Properties

class ParksForm(forms.ModelForm):
    class Meta:
        model=Parks
        fields = ('Park_Name','Park_Address','County','Park_Image')
        labels= {'Park_Name': 'Park Name',
                 'Park_Address': 'Address',
                'County': 'County',
                'Park_Image':'Photo'
                 }

class ParkPropertyForm(forms.ModelForm):
    class Meta:
        model=Park_Properties
        fields = ('Park_Name','Property_Name','Property_Description','Property_Guest_Capacity','Property_Location','Slot','Price','Property_Image')
        labels= {'Park_Name': 'Park Name',
                 'Property_Name':'Property_Name',
                 'Property_Description': 'Description',
                'Property_Guest_Capacity': 'Guest Capacity',
                'Property_Location':'Location',
                 'Slot':'Slot',
                 'Price':'Price',
                  'Property_Image':'photo'
                 }


class ParkPropertyForm1(forms.ModelForm):
    class Meta:
        model=Park_Properties
        fields = ('Park_Name','Property_Name','Property_Description','Property_Guest_Capacity','Property_Location','Slot','Price','Property_Image')
        labels= {'Park_Name': 'Park Name',
                 'Property_Name':'Property_Name',
                 'Property_Description': 'Description',
                'Property_Guest_Capacity': 'Guest Capacity',
                'Property_Location':'Location',
                 'Slot':'Slot',
                 'Price':'Price',
                  'Property_Image':'photo'
                 }

    def __init__(self,Park_Name ,*args, **kwargs):
        super(ParkPropertyForm1, self).__init__(*args, **kwargs)
        # access object through self.instance...
        self.fields['Park_Name'].queryset = Parks.objects.filter(Park_Name=Park_Name)

aafield/aafieldapp/views.py
# Create your views here.
import email

import braintree
from aafield import settings
from aafieldapp.models import Parks, Property_Status,Park_Properties,Reservation,Profile, Transaction
from django.contrib.auth.decorators import login_required
from django import forms
from django.core.mail import EmailMessage
from django.db.models import Q
from django.http import HttpResponse
from django.utils import timezone
from aafieldapp.decorators import employee_required, customer_required, maintenanceperson_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from .forms import ParksForm,ParkPropertyForm,ParkPropertyForm1
from accounts.forms import UserLoginForm
from accounts.models import CustomUser
import datetime

braintree.Configuration.configure(
    braintree.Environment.Sandbox,
    merchant_id=settings.BRAINTREE_MERCHANT_ID,
    public_key=settings.BRAINTREE_PUBLIC_KEY,
    private_key=settings.BRAINTREE_PRIVATE_KEY,
)

@login_required
def home(request):
    current_user = request.user
    if(current_user.is_superuser):
        return render(request, 'aafieldapp/home.html')
    elif(current_user.profile.is_customer):
        parks = Parks.objects.all()
        context = {'parks': parks}
        return render(request, 'aafieldapp/customerhome.html', context)
    elif(current_user.profile.is_employee):
        parks=Parks.objects.all()
        context = {'parks': parks}
        return render(request, 'aafieldapp/employeehome.html',context)
    elif (current_user.profile.is_maintenanceperson):
        property_status = maintenancehome(request)
        return render(request, 'aafieldapp/maintenancepersonhome.html', {'property_status': property_status})

@login_required
@maintenanceperson_required
def maintenancehome(request):
    current_user = request.user
    property_status = Property_Status.objects.select_related('Reservation_ID').filter(Maintenance_ID=current_user.id,Reservation_ID__Status='Assigned Maintenance')
    print(property_status)
    return property_status

def search(request):
    if request.method == 'GET':
        park= request.GET.get('Park')
        County= request.GET.get('Location')
        submitbutton= request.GET.get('submit')
        parks=Parks.objects.all()
        context = {'parks': parks}
        if park is not None and park!="":
            park_list= Parks.objects.filter(Park_Name=park)
            pid = Parks.objects.values_list('id', flat=True).filter(Park_Name=park)
            prop=Park_Properties.objects.filter(Park_Name=pid[0])
            context={'park_list':park_list,'prop':prop}
            return render(request, 'aafieldapp/park_view.html', context)
        elif County is not None and County!="":
            park_list= Parks.objects.filter(County=County)
            context={'park_list':park_list}
            return render(request, 'aafieldapp/park_view.html', context)
        else:
            return render(request, 'aafieldapp/search.html',context)
    else:
        return render(request, 'aafieldapp/search.html',context)

def parkview(request,id):
    park_list=Parks.objects.filter(pk=id)
    pid = Parks.objects.values_list('id', flat=True).filter(pk=id)
    prop = Park_Properties.objects.filter(Park_Name=pid[0])
    context = {'park_list': park_list,'prop':prop}
    return render(request, 'aafieldapp/park_view.html', context)

def propertyview(request,id,pid):
    if request.user.is_authenticated:
        if request.method == 'POST' and 'viewslot' in request.POST:
            event_date = request.POST.get('Event_Date')
            park_name = pid
            property_id = id
            park_id = Parks.objects.values_list('id', flat=True).filter(Park_Name=park_name)
            park_id=park_id[0]
            if event_date is not None and event_date != '':
              unavail_slot=Reservation.objects.values_list('Slot',flat=True).filter(Park_Name=park_id,Property_Name=property_id,Event_Date=event_date, Status__in =('Booked','Assigned Maintenance','Added Comments'))
              slot=['8 am - 10 am','10 am - 12 pm','12 pm - 2 pm','2 pm - 4 pm']
              avail_slot=[]
              unavail_slot = [entry for entry in unavail_slot]
              current_date = datetime.date.today().strftime('%Y-%m-%d')
              current_hour = datetime.datetime.today().hour
              if current_date == event_date and current_hour >= 8 and current_hour < 10:
                  temp_slot = ['8 am - 10 am']
              elif current_date == event_date and current_hour >= 10 and current_hour < 12:
                  temp_slot = ['8 am - 10 am', '10 am - 12 pm']
              elif current_date == event_date and current_hour >= 12 and current_hour < 14:
                  temp_slot = ['8 am - 10 am', '10 am - 12 pm', '12 pm - 2 pm']
              elif current_date == event_date and current_hour >= 14 and current_hour < 16:
                  temp_slot = ['8 am - 10 am', '10 am - 12 pm', '12 pm - 2 pm', '2 pm - 4 pm']
              else:
                  temp_slot = []
              print("slot",temp_slot)
              print("unavail_slot",unavail_slot)
              final_unavail_slot = list(set(unavail_slot) | set(temp_slot))
              print("final_unavail_slot",final_unavail_slot)
              #x = set(slot)
              #y = set(final_unavail_slot)
              avail_slot = [i for i in slot + final_unavail_slot if i not in slot or i not in final_unavail_slot]
              # take difference of two lists
              #avail_slot=[]
              #avail_slot = x.difference(y)
              prop = Park_Properties.objects.get(pk=id)
              park = Parks.objects.get(pk=park_id)
              park_address=request.POST.get('park_address')
              context ={'slot':slot,'prop':prop,'event_date':event_date,'park':park,'unavail_slot':final_unavail_slot,'avail_slot':avail_slot}
              return render(request, "aafieldapp/reserve.html", context)
            else:
                prop = Park_Properties.objects.filter(pk=id)
                reserve = Reservation.objects.all()
                current_date = datetime.date.today().strftime('%Y-%m-%d')
                NextDay_Date = datetime.date.today() + datetime.timedelta(days=1)
                NextDay_Date=NextDay_Date.strftime('%Y-%m-%d')
                current_hour = datetime.datetime.today().hour
                if current_hour < 14:
                    current_date = current_date
                else:
                    current_date = NextDay_Date
                context = {'prop': prop, 'reserve': reserve,'current_date':current_date}
                return render(request, "aafieldapp/property_view.html", context)
        elif request.method == 'POST' and 'reserve' in request.POST:
            park_name = request.POST.get('park_name')
            property_name = request.POST.get('property_name')
            park_address = request.POST.get('park_address')
            event_date = request.POST.get('event_date')
            slot = request.POST.get('slot')
            customer_name = request.user
            reservation=Reservation()
            reservation.Park_Name = Parks.objects.get(Park_Name=park_name.strip())
            park_id = Parks.objects.values_list('id', flat=True).filter(Park_Name=park_name.strip())
            reservation.Property_Name = Park_Properties.objects.get(Property_Name = property_name.strip(), Park_Name = park_id[0])
            reservation.Customer_Name = CustomUser.objects.get(username=customer_name)
            reservation.Event_Date = event_date
            reservation.Slot = slot
            reservation.Status = 'Processing'
            if slot == '8 am - 10 am'or slot=='10 am - 12 pm'or slot=='12 pm - 2 pm'or slot=='2 pm - 4 pm':
                reservation.save()
                reserve_id = reservation.id
                braintree_client_token = braintree.ClientToken.generate()
                context={'braintree_client_token':braintree_client_token, 'reserve_id':reserve_id,'park_name':park_name.strip(),'property_name':property_name.strip(),'park_address':park_address,'event_date':event_date,'slot':slot}
                return render(request, "aafieldapp/checkout.html",context)
            else:
                context = {'slot': slot, 'prop': prop, 'event_date': event_date, 'park': park, 'unavail_slot': unavail_slot, 'avail_slot': avail_slot}
                return render(request, "aafieldapp/reserve.html", context)
        else:
            prop = Park_Properties.objects.filter(pk=id)
            reserve = Reservation.objects.all()
            current_date = datetime.date.today().strftime('%Y-%m-%d')
            NextDay_Date = datetime.date.today() + datetime.timedelta(days=1)
            NextDay_Date = NextDay_Date.strftime('%Y-%m-%d')
            current_hour = datetime.datetime.today().hour
            if current_hour < 16:
                current_date = current_date
            else:
                current_date=NextDay_Date
            context = {'prop': prop, 'reserve': reserve,'current_date':current_date}
            return render(request, "aafieldapp/property_view.html", context)
    else:
        form = UserLoginForm()
        return redirect("/accounts/login/")

@login_required
@employee_required
def emppropertyview(request,id):
    prop=Park_Properties.objects.filter(pk=id)
    context = {'prop': prop}
    return render(request, 'aafieldapp/empproperty_view.html', context)

@login_required
@employee_required
def empparkview(request,id):
    park_list=Parks.objects.filter(pk=id)
    pid = Parks.objects.values_list('id', flat=True).filter(pk=id)
    prop = Park_Properties.objects.filter(Park_Name=pid[0])
    context = {'park_list': park_list,'prop':prop}
    return render(request, 'aafieldapp/emppark_view.html', context)

@login_required
@employee_required
def updateparkview(request,id=0):
    if request.method=="GET":
        if id==0:
          form=ParksForm()
        else:

aafield/aafieldapp/templates/aafieldapp/AddPark.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 ">
            <div class="panel panel-default" style="width: 600px; height:500px">
                <div class="panel-heading">
                    <h5><b>Park</b></h5>
                </div>
            <div class="panel-body">
           <!-- Full Page Intro -->
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            {{ form.Park_Name|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            {{ form.Park_Address|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            {{ form.County|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            {{ form.Park_Image|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row text-center">
                        <button class="btn btn-primary "  type="submit" name="add park">Submit</button>
                    </div>
                </form>
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

aafield/aafieldapp/templates/aafieldapp/Addproperty.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 ">
            <div class="panel panel-default" style="width: 600px; height:600px">
                <div class="panel-heading">    <h5><b>Add Property</b></h5> </div>
                <div class="panel-body">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-12 mb-0">
                                {{ form.Park_Name|as_crispy_field }}

                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12 mb-0">
                                {{ form.Property_Name|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-row">
                             <div class="form-group col-md-12 mb-0">
                                 {{ form.Property_Description|as_crispy_field }}
                             </div>
                        </div>
                        <div class="form-row">
                             <div class="form-group col-md-12 mb-0">
                                 {{ form.Property_Location|as_crispy_field }}
                             </div>
                        </div>
                        <div class="form-row">
                             <div class="form-group col-md-12 mb-0">
                                 {{ form.Property_Guest_Capacity|as_crispy_field }}
                             </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12 mb-0">
                                {{ form.Price|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12 mb-0">
                                {{ form.Property_Image|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-row text-center">
                            <button class="btn btn-primary "  type="submit" name="add property"> Add Property</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

aafield/aafieldapp/templates/aafieldapp/addcharges.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Add Charges
{% endblock %}
{% block content %}
<div class="container-1">
    <div class="row pt-5 pl-5">
        <div class="col-md-10 ">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong class="">Add Maintenance Charges </strong>
                </div>
                <div class="panel-body">
                <form action="/finalPayment" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="Park">Park Name</label>
                               <input type="text" class="form-control" id="Park"  value=" {{property_status.Park_Name}} " name="park_name">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="Property">Property Name</label>
                               <input type="text" class="form-control" id="property"  value="{{property_status.Property_Name}} "name="property_name">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="Park">Reservation ID</label>
                               <input type="text" class="form-control" id="park"  value={{property_status.Reservation_ID.id}} name="res_id">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="Park">Comments</label>
                               <input type="text" class="form-control" id="park"  value=" {{property_status.Property_Status_Description}} "name="comments">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="Park">Report Time</label>
                               <input type="text" class="form-control" id="park"  value=" {{property_status.Report_TimeDate}} "name="reporttime">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="Park">Additional Charges</label>
                               <input type="text" class="form-control" id="park" value="" placeholder="Enter Charges" name="expenses">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="Park">Maintenance Person</label>
                               <input type="text" class="form-control" id="park"  value={{property_status.Maintenance_ID}} name="maint_id">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-row text-center">
                            <button class="btn btn-primary" type="submit">Add Charges</button>
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

aafield/aafieldapp/templates/aafieldapp/customerhome.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        {% for parks in parks %}
            <div class="col-lg-4 col-sm-6">
                <div class="card h-100">
                    <h4 class="card-title">
                        <a href="{% url 'aafieldapp:parkview' id=parks.id %}"><b>{{parks.Park_Name}}</b></a>
                    </h4>
                    <a href="{% url 'aafieldapp:parkview' id=parks.id %}"><img class="card-img-top" src={{parks.Park_Image.url}} alt=""></a>
                    <div class="card-body">
                        <p></p>
                        <p class="card-text"><b>Address: </b>{{parks.Park_Address}}</p>
                        <p></p>
                        <p class="card-text"><b>County:</b>{{parks.County}}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

aafield/aafieldapp/templates/aafieldapp/employeehome.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
         {% for parks in parks %}
            <div class="col-lg-4 col-sm-6">
                <div class="card h-100">
                    <h4 class="card-title">
                        <a href="{% url 'aafieldapp:employeeparkview' id=parks.id %}"><b>{{parks.Park_Name}}</b></a>
                    </h4>
                    <a href="{% url 'aafieldapp:employeeparkview' id=parks.id %}"><img class="card-img-top" src={{parks.Park_Image.url}} alt=""></a>
                    <div class="card-body">
                        <p></p>
                        <p class="card-text"><b>Address: </b>{{parks.Park_Address}}</p>
                        <p></p>
                        <p class="card-text"><b>County:</b>{{parks.County}}</p>
                    </div>
                </div>
            </div>
          {% endfor %}
    </div>
</div>
{% endblock %}

aafield/aafieldapp/templates/aafieldapp/emppark_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    {% for park_list in park_list %}
        <div class="row">
            <div class="col-lg-4 col-sm-6 portfolio-item">
                <div class="panel panel-default" style="width: 600px; height:700px">
                    <div class="panel-header pt-3">
                        <h5><b>{{park_list.Park_Name}}</b></h5>
                    </div>
                    <div class="panel-body">
                        <p></p>
                        <a href="#"><img class="card-img-top" src={{park_list.Park_Image.url}} alt=""style="width: 500px;"></a>
                        <P> </P>
                        <p class="text pt-3"><b>Address: </b>{{park_list.Park_Address}}</p>
                        <p> </p>
                        <p class="text pt-3"><b>County: </b>{{park_list.County}}</p>
                        <p></p>
                        <p></p>
                        <h5><b>Park Properties:</b></h5>
                        {% for prop in prop %}
                            <a href="{% url 'aafieldapp:emppropertyview' id=prop.id %}">{{prop.Property_Name}}</a>
                            <p></p>
                        {% endfor %}
                        <p></p>
                        <p></p>
                        <p>
                        <a href="{% url 'aafieldapp:updatepark' id=park_list.id %}">Edit Park |</a>
                        <a href="{% url 'aafieldapp:deletepark' id=park_list.id %}">Delete Park |</a>
                        <a href="{% url 'aafieldapp:addproperty' id=park_list.id %}">Add Property</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

aafield/aafieldapp/templates/aafieldapp/maintenancepersonhome.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
</head>
<body>
<div class="container-1">
  <div class="row pt-5 pl-5">
    <div class="col-md-10 ">
       <div class="panel panel-default" style="width: 900px">
           <div class="panel-body">
    {% if property_status %}
        <div class="row">
            <h2 style="padding-left: 15Px">Parks assigned to you for maintenance</h2>
        </div>
        <div>
            <table class="table table-striped table-bordered ">
                <thead>
                <tr class="bg-info">
                    <th>Reservation Id</th>
                    <th>Customer Name</th>
                    <th>Park Name</th>
                    <th>Property Name</th>
                    <th>Event Date</th>
                    <th>Slot</th>
                    <th>Comments</th>
                </tr>
                </thead>
                <tbody>
                {% for property_status in property_status %}
                    <tr>
                        <td>{{ property_status.Reservation_ID.id }}</td>
                        <td>{{ property_status.Reservation_ID.Customer_Name }}</td>
                        <td>{{ property_status.Park_Name }}</td>
                        <td>{{ property_status.Property_Name }}</td>
                        <td>{{ property_status.Reservation_ID.Event_Date }}</td>
                        <td>{{ property_status.Reservation_ID.Slot }}</td>
                        <td><a href="{% url 'aafieldapp:addComments' id=property_status.id%}">Add Comments</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p style="font-size:25px;">No Properties assigned for maintenance</p>
    {% endif %}
</div>
       </div>
   </div>
 </div>
</div>
</body>
</html>
{% endblock %}

aafield/aafieldapp/templates/aafieldapp/viewCustomerbookings.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
</head>
<body>
<div class="container-1">
  <div class="row pt-5 pl-5">
    <div class="col-md-10 ">
       <div class="panel panel-default" style="width: 900px">
           <div class="panel-body">
           {% if reserve %}
                <div class="row">
                 <h2 style="padding-left: 15Px">Bookings</h2>
                </div>
                <div>
               <table class="table table-striped table-bordered ">
                <thead>
                   <tr class="bg-info">
                      <th>Reservation Id</th>
                      <th>Park Name</th>
                      <th>Property Name</th>
                      <th>Event Date</th>
                      <th>Slot</th>
                      <th>Status</th>
                      <th>Cancel</th>
                   </tr>
                </thead>
                <tbody>
                   {% for reserve in reserve %}
                     <tr>
                        <td>{{ reserve.id }}</td>
                        <td>{{ reserve.Park_Name }}</td>
                        <td>{{ reserve.Property_Name }}</td>
                        <td>{{ reserve.Event_Date }}</td>
                        <td>{{ reserve.Slot }}</td>
                        <td>{{ reserve.Status }}</td>
                        {% if  reserve.Status != 'Cancelled' and reserve.Status != 'Payment Done' %}
                            <td><a href="{% url 'aafieldapp:cancelBooking' id=reserve.id%}">Cancel</a></td>
                        {% endif %}
                     </tr>
                   {% endfor %}
                </tbody>
                </table>
                </div>
    {% else %}
        <p style="font-size:25px;">No bookings yet</p>
    {% endif %}
</div>
       </div>
   </div>
 </div>
</div>
</body>
</html>
{% endblock %}